// Generated by Dagger (https://dagger.dev).
package pe.com.starcode.testprojectbase.general.di.component;

import dagger.android.AndroidInjector;
import dagger.android.DaggerApplication_MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import dagger.android.DispatchingAndroidInjector_Factory;
import dagger.internal.Preconditions;
import java.util.Collections;
import javax.inject.Provider;
import pe.com.starcode.testprojectbase.application.AppBase;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DaggerAppComponent implements AppComponent {
  private DaggerAppComponent(AppBase application) {

  }

  public static AppComponent.Builder builder() {
    return new Builder();
  }

  private DispatchingAndroidInjector<Object> getDispatchingAndroidInjectorOfObject() {
    return DispatchingAndroidInjector_Factory.newInstance(Collections.<Class<?>, Provider<AndroidInjector.Factory<?>>>emptyMap(), Collections.<String, Provider<AndroidInjector.Factory<?>>>emptyMap());
  }

  @Override
  public void inject(AppBase app) {
    injectAppBase(app);
  }

  private AppBase injectAppBase(AppBase instance) {
    DaggerApplication_MembersInjector.injectAndroidInjector(instance, getDispatchingAndroidInjectorOfObject());
    return instance;
  }

  private static final class Builder implements AppComponent.Builder {
    private AppBase application;

    @Override
    public Builder application(AppBase app) {
      this.application = Preconditions.checkNotNull(app);
      return this;
    }

    @Override
    public AppComponent build() {
      Preconditions.checkBuilderRequirement(application, AppBase.class);
      return new DaggerAppComponent(application);
    }
  }
}
